<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Optimize>true</Optimize>
    <RootNamespace>Mia.Emulator.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AvrCore/AvrCore.csproj" />
    <ProjectReference Include="../Mia.Emulator/Mia.Emulator.csproj" />
  </ItemGroup>

</Project>
