// SPDX-License-Identifier: MIT

namespace Mia.Emulator.Gsm;

internal sealed record MiaLiveGsmStatus(
    bool Running,
    bool Registered,
    long ExecutedInstructions,
    long Cycles,
    long QueuedIncomingSms,
    long QueuedIncomingCalls,
    long PagingRequests,
    long PagingResponses,
    long DeliveredIncomingSms,
    long IncomingCallSetups,
    long IncomingCallConfirmed,
    long IncomingCallConnects,
    long IncomingCallDisconnects,
    long IncomingCallReleaseCompletes,
    long TrafficAssignments,
    long TrafficAssignmentsDelivered,
    long TrafficAssignmentsComplete,
    long MobileReleases,
    long DedicatedUplinks,
    long DedicatedUplinkInformation,
    long Sabms,
    long Uas,
    long CipherCommands,
    long CipherCompletes,
    long MobileTerminatedSapi3Establishments,
    long MobileTerminatedSms,
    byte RrState,
    byte MmmState,
    byte MphState,
    byte PhCallbackState,
    byte ChannelDecoderState,
    long RrStateSeenMask,
    long MphStateSeenMask,
    long IdlePagingDecodes,
    long AcquisitionDecodes,
    long DedicatedDownlinkDecodes,
    int FrameVersion,
    byte RssiLevel,
    byte RssiWidgetByte,
    int NativeRssiWriterPc,
    int RssiWidgetWriterPc,
    ushort RfRawSample,
    ushort CarrierRawSample,
    long RssiSampleCount,
    long AdcCompletions,
    long AdcResultReads,
    int RssiAdcPending,
    bool IncomingTransactionActive,
    int DeferredIncomingTransactions)
{
    public static MiaLiveGsmStatus Stopped { get; } = new(
        false, false, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, false, 0);
}
