// <auto-generated />
// Generated by tools/generate-mia-phone-geometry.cs from the PDF-derived paths in mia.svg.

using Avalonia;
using Avalonia.Media;

namespace Mia.App.Controls;

internal static class MiaPhoneGeometry
{
    internal const string SourceSha256 = "47687da1e55abaea499c01bf51ad5400abd13abe972b90733dd0b56deddb0bd1";
    internal const double CanvasWidth = 470;
    internal const double CanvasHeight = 958;

    internal static Geometry CreateKey(int index) => index switch
    {
        0 => CreateKey0(),
        1 => CreateKey1(),
        2 => CreateKey2(),
        3 => CreateKey3(),
        4 => CreateKey4(),
        5 => CreateKey5(),
        6 => CreateKey6(),
        7 => CreateKey7(),
        8 => CreateKey8(),
        9 => CreateKey9(),
        10 => CreateKey10(),
        11 => CreateKey11(),
        12 => CreateKey12(),
        13 => CreateKey13(),
        14 => CreateKey14(),
        15 => CreateKey15(),
        _ => throw new ArgumentOutOfRangeException(nameof(index)),
    };

    internal static StreamGeometry CreatePhoneBody()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(228.773881, 955.314651), true);
            context.CubicBezierTo(new Point(228.773881, 955.314651), new Point(407.436539, 953.408916), new Point(429.78561, 935.347746));
            context.CubicBezierTo(new Point(438.729575, 928.157925), new Point(446.547415, 927.031808), new Point(444.879898, 903.751526));
            context.CubicBezierTo(new Point(443.190727, 880.471237), new Point(433.142303, 705.836608), new Point(436.498996, 674.240388));
            context.CubicBezierTo(new Point(439.855689, 642.644168), new Point(468.333434, 421.448969), new Point(466.644258, 321.657754));
            context.CubicBezierTo(new Point(464.976741, 221.866539), new Point(449.644239, 105.443454), new Point(436.239122, 68.021747));
            context.CubicBezierTo(new Point(432.904089, 58.709634), new Point(430.825105, 43.442099), new Point(414.474763, 34.758009));
            context.CubicBezierTo(new Point(408.064565, 31.358005), new Point(384.069627, 30.058639), new Point(376.771529, 27.265004));
            context.CubicBezierTo(new Point(342.338364, 14.098107), new Point(301.884804, 4.352874), new Point(241.052878, 3.44332));
            context.CubicBezierTo(new Point(183.924138, 2.577074), new Point(125.539344, 15.354165), new Point(89.481972, 28.109596));
            context.CubicBezierTo(new Point(79.043746, 31.791125), new Point(62.043722, 30.188574), new Point(55.135432, 36.425527));
            context.CubicBezierTo(new Point(45.931599, 44.741465), new Point(39.218213, 57.215365), new Point(35.038589, 68.021747));
            context.CubicBezierTo(new Point(23.474243, 97.842168), new Point(4.30861, 221.866539), new Point(2.619439, 321.657754));
            context.CubicBezierTo(new Point(0.951922, 421.448969), new Point(29.429662, 642.644168), new Point(32.786355, 674.240388));
            context.CubicBezierTo(new Point(36.121393, 705.836608), new Point(26.072975, 880.471237), new Point(24.405453, 903.751526));
            context.CubicBezierTo(new Point(22.737936, 927.031808), new Point(31.097184, 929.262382), new Point(39.478086, 935.347746));
            context.CubicBezierTo(new Point(62.736713, 952.282799), new Point(240.489816, 955.314651), new Point(240.489816, 955.314651));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateScreenWindow()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(86.94821, 480.201915), true);
            context.CubicBezierTo(new Point(86.94821, 480.201915), new Point(65.985127, 265.698442), new Point(82.487058, 232.954451));
            context.CubicBezierTo(new Point(83.591523, 230.745532), new Point(88.07433, 226.306038), new Point(95.892175, 225.201575));
            context.CubicBezierTo(new Point(103.68836, 224.075458), new Point(376.186812, 225.201575), new Point(376.186812, 225.201575));
            context.CubicBezierTo(new Point(376.186812, 225.201575), new Point(388.46581, 224.075458), new Point(390.718043, 235.163371));
            context.CubicBezierTo(new Point(402.997041, 257.339197), new Point(395.179196, 448.042634), new Point(386.235236, 479.097452));
            context.CubicBezierTo(new Point(376.186812, 489.080908), new Point(92.535482, 490.185365), new Point(86.94821, 480.201915));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateTopCornerLeft()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(64.599139, 72.179716), true);
            context.CubicBezierTo(new Point(67.392775, 72.742772), new Point(77.766037, 61.784794), new Point(80.516358, 53.880329));
            context.CubicBezierTo(new Point(83.02846, 46.668854), new Point(79.693427, 34.758009), new Point(76.336734, 32.267559));
            context.CubicBezierTo(new Point(72.980041, 29.777108), new Point(66.28831, 37.24846), new Point(66.28831, 37.24846));
            context.CubicBezierTo(new Point(66.28831, 37.24846), new Point(61.805503, 71.616655), new Point(64.599139, 72.179716));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateTopCornerRight()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(411.746097, 72.179716), true);
            context.CubicBezierTo(new Point(408.974121, 72.742772), new Point(398.579198, 61.784794), new Point(395.828877, 53.880329));
            context.CubicBezierTo(new Point(393.316775, 46.668854), new Point(395.828877, 32.267559), new Point(400.030156, 32.267559));
            context.CubicBezierTo(new Point(401.870927, 32.267559), new Point(410.814886, 40.020435), new Point(410.814886, 40.020435));
            context.CubicBezierTo(new Point(410.814886, 40.020435), new Point(414.539733, 71.616655), new Point(411.746097, 72.179716));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateSideRocker()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(29.278073, 88.096935), true);
            context.CubicBezierTo(new Point(28.563422, 86.602666), new Point(20.312453, 100.4409), new Point(18.298439, 107.002691));
            context.CubicBezierTo(new Point(16.306079, 113.564483), new Point(16.197799, 116.054933), new Point(12.797797, 116.72627));
            context.CubicBezierTo(new Point(9.419449, 117.397608), new Point(14.227094, 121.793793), new Point(14.227094, 121.793793));
            context.CubicBezierTo(new Point(14.227094, 121.793793), new Point(11.260215, 148.279182), new Point(16.176145, 151.007844));
            context.CubicBezierTo(new Point(21.07042, 153.758166), new Point(25.748131, 126.493163), new Point(25.748131, 126.493163));
            context.CubicBezierTo(new Point(25.748131, 126.493163), new Point(32.851325, 95.481658), new Point(29.278073, 88.096935));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateJoystickOuter()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(238.973894, 537.027466), true);
            context.CubicBezierTo(new Point(253.180282, 537.027466), new Point(262.643989, 545.75487), new Point(261.864367, 556.647874));
            context.CubicBezierTo(new Point(261.063097, 567.540883), new Point(249.238877, 579.170198), new Point(238.973894, 579.170198));
            context.CubicBezierTo(new Point(228.708911, 579.170198), new Point(216.083415, 567.540883), new Point(216.083415, 556.647874));
            context.CubicBezierTo(new Point(216.083415, 545.75487), new Point(224.767506, 537.027466), new Point(238.973894, 537.027466));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateJoystickInner()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(255.930603, 558.098835), true);
            context.CubicBezierTo(new Point(255.930603, 566.17655), new Point(248.329321, 572.716687), new Point(238.973894, 572.716687));
            context.CubicBezierTo(new Point(229.596811, 572.716687), new Point(221.995525, 566.17655), new Point(221.995525, 558.098835));
            context.CubicBezierTo(new Point(221.995525, 550.021114), new Point(229.596811, 543.480982), new Point(238.973894, 543.480982));
            context.CubicBezierTo(new Point(248.329321, 543.480982), new Point(255.930603, 550.021114), new Point(255.930603, 558.098835));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateLegend4()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(86.558405, 523.059299), true);
            context.CubicBezierTo(new Point(90.456499, 520.092412), new Point(96.390262, 517.450373), new Point(101.024666, 517.688591));
            context.CubicBezierTo(new Point(102.648873, 519.139545), new Point(103.450147, 520.33063), new Point(104.446324, 521.933177));
            context.LineTo(new Point(98.122748, 525.224902));
            context.CubicBezierTo(new Point(95.913831, 521.543371), new Point(92.318919, 523.037639), new Point(88.680698, 525.809617));
            context.CubicBezierTo(new Point(85.020822, 528.581595), new Point(82.72528, 531.873319), new Point(85.605537, 534.710267));
            context.LineTo(new Point(80.732915, 539.886072));
            context.CubicBezierTo(new Point(79.45521, 538.521737), new Point(78.502343, 537.438936), new Point(77.50616, 535.511541));
            context.CubicBezierTo(new Point(78.523998, 531.007076), new Point(82.681965, 526.026181), new Point(86.558405, 523.059299));
            context.EndFigure(false);
        }

        return geometry;
    }

    internal static StreamGeometry CreateLegend5()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(384.697656, 522.25802), true);
            context.CubicBezierTo(new Point(389.938425, 522.279675), new Point(396.673467, 523.925542), new Point(400.441622, 527.108982));
            context.CubicBezierTo(new Point(400.853089, 529.382869), new Point(400.74481, 530.920452), new Point(400.528247, 532.891157));
            context.LineTo(new Point(393.035246, 531.570137));
            context.CubicBezierTo(new Point(393.598301, 527.044018), new Point(389.591928, 525.982866), new Point(384.675996, 525.961211));
            context.CubicBezierTo(new Point(379.781725, 525.917896), new Point(375.667067, 527.195606), new Point(376.251782, 531.440198));
            context.LineTo(new Point(368.737121, 532.652938));
            context.CubicBezierTo(new Point(368.542218, 530.660579), new Point(368.455594, 529.144656), new Point(368.91037, 526.870769));
            context.CubicBezierTo(new Point(372.72184, 523.730633), new Point(379.500197, 522.236365), new Point(384.697656, 522.25802));
            context.EndFigure(false);
        }

        return geometry;
    }

    internal static StreamGeometry CreateLegend6()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(389.873455, 534.038927), true);
            context.LineTo(new Point(387.924411, 535.100074));
            context.LineTo(new Point(378.374076, 517.86184));
            context.LineTo(new Point(380.301471, 516.822348));
            context.LineTo(new Point(389.873455, 534.038927));
            context.EndFigure(false);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey0()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(69.081946, 553.399465), true);
            context.CubicBezierTo(new Point(69.081946, 553.399465), new Point(60.137987, 511.256733), new Point(65.725253, 509.026154));
            context.CubicBezierTo(new Point(71.312525, 506.817234), new Point(150.595432, 520.114072), new Point(156.182699, 526.78414));
            context.CubicBezierTo(new Point(161.769971, 533.432559), new Point(162.896085, 560.047878), new Point(178.531776, 582.223704));
            context.CubicBezierTo(new Point(191.48211, 600.609719), new Point(213.13819, 605.503992), new Point(213.13819, 609.943491));
            context.CubicBezierTo(new Point(213.13819, 614.361331), new Point(213.13819, 621.009744), new Point(213.13819, 621.009744));
            context.CubicBezierTo(new Point(213.13819, 621.009744), new Point(176.73432, 600.111631), new Point(132.729163, 568.905217));
            context.CubicBezierTo(new Point(117.093478, 557.817304), new Point(69.081946, 553.399465), new Point(69.081946, 553.399465));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey1()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(408.15119, 553.399465), true);
            context.CubicBezierTo(new Point(408.15119, 553.399465), new Point(417.09515, 511.256733), new Point(411.507883, 509.026154));
            context.CubicBezierTo(new Point(405.920611, 506.817234), new Point(326.637704, 520.114072), new Point(321.050437, 526.78414));
            context.CubicBezierTo(new Point(315.463165, 533.432559), new Point(314.358706, 560.047878), new Point(298.723015, 582.223704));
            context.CubicBezierTo(new Point(285.751026, 600.609719), new Point(264.094946, 605.503992), new Point(264.094946, 609.943491));
            context.CubicBezierTo(new Point(264.094946, 614.361331), new Point(264.094946, 621.009744), new Point(264.094946, 621.009744));
            context.CubicBezierTo(new Point(264.094946, 621.009744), new Point(294.218553, 601.216088), new Point(338.223705, 570.00968));
            context.CubicBezierTo(new Point(353.859395, 558.921767), new Point(408.15119, 553.399465), new Point(408.15119, 553.399465));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey2()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(62.36856, 585.537086), true);
            context.CubicBezierTo(new Point(63.49468, 579.99313), new Point(83.591523, 577.78421), new Point(108.171173, 584.432629));
            context.CubicBezierTo(new Point(132.772478, 591.102697), new Point(149.490973, 603.273418), new Point(145.00816, 613.256868));
            context.CubicBezierTo(new Point(140.547008, 623.240324), new Point(110.401746, 619.905287), new Point(92.535482, 612.152411));
            context.CubicBezierTo(new Point(74.669218, 604.377875), new Point(61.264101, 591.081043), new Point(62.36856, 585.537086));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey3()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(70.706153, 646.412325), true);
            context.CubicBezierTo(new Point(72.373669, 635.216131), new Point(100.981354, 633.288742), new Point(124.911323, 642.081113));
            context.CubicBezierTo(new Point(148.841286, 650.873478), new Point(164.606916, 660.835274), new Point(162.896085, 670.905352));
            context.CubicBezierTo(new Point(161.163599, 680.997089), new Point(128.073106, 680.520655), new Point(109.275632, 675.344851));
            context.CubicBezierTo(new Point(89.178789, 669.800895), new Point(69.060291, 657.586865), new Point(70.706153, 646.412325));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey4()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(72.936732, 704.060809), true);
            context.CubicBezierTo(new Point(74.604248, 692.886274), new Point(103.211928, 690.958885), new Point(127.141896, 699.751251));
            context.CubicBezierTo(new Point(151.071865, 708.521962), new Point(166.83749, 718.505418), new Point(165.126658, 728.575495));
            context.CubicBezierTo(new Point(163.394172, 738.645573), new Point(130.303685, 738.190793), new Point(111.506206, 733.014989));
            context.CubicBezierTo(new Point(91.409362, 727.471032), new Point(71.290865, 715.235349), new Point(72.936732, 704.060809));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey5()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(77.419539, 761.709298), true);
            context.CubicBezierTo(new Point(79.087055, 750.534758), new Point(107.67308, 748.607369), new Point(131.603049, 757.399734));
            context.CubicBezierTo(new Point(155.554672, 766.192105), new Point(171.298642, 776.153901), new Point(169.587811, 786.223979));
            context.CubicBezierTo(new Point(167.876985, 796.31571), new Point(134.764838, 795.839277), new Point(115.989018, 790.663473));
            context.CubicBezierTo(new Point(95.870515, 785.119516), new Point(75.752017, 772.905487), new Point(77.419539, 761.709298));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey6()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(75.18896, 818.08007), true);
            context.CubicBezierTo(new Point(76.834822, 806.905535), new Point(105.442507, 804.97814), new Point(129.372475, 813.770512));
            context.CubicBezierTo(new Point(153.302444, 822.541223), new Point(169.068069, 832.524679), new Point(167.357237, 842.594756));
            context.CubicBezierTo(new Point(165.624751, 852.664828), new Point(132.534259, 852.210054), new Point(113.758439, 847.03425));
            context.CubicBezierTo(new Point(93.639941, 841.490294), new Point(73.521444, 829.25461), new Point(75.18896, 818.08007));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey7()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(416.380498, 585.537086), true);
            context.CubicBezierTo(new Point(415.276039, 579.99313), new Point(395.179196, 577.78421), new Point(370.599545, 584.432629));
            context.CubicBezierTo(new Point(345.97658, 591.102697), new Point(329.279745, 603.273418), new Point(333.740898, 613.256868));
            context.CubicBezierTo(new Point(338.223705, 623.240324), new Point(368.368972, 619.905287), new Point(386.235236, 612.152411));
            context.CubicBezierTo(new Point(404.1015, 604.377875), new Point(417.506612, 591.081043), new Point(416.380498, 585.537086));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey8()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(408.042905, 646.412325), true);
            context.CubicBezierTo(new Point(406.397044, 635.216131), new Point(377.789364, 633.288742), new Point(353.859395, 642.081113));
            context.CubicBezierTo(new Point(329.929427, 650.873478), new Point(314.163802, 660.835274), new Point(315.874633, 670.905352));
            context.CubicBezierTo(new Point(317.60712, 680.997089), new Point(350.697606, 680.520655), new Point(369.495086, 675.344851));
            context.CubicBezierTo(new Point(389.591929, 669.800895), new Point(409.710427, 657.586865), new Point(408.042905, 646.412325));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey9()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(405.812332, 704.060809), true);
            context.CubicBezierTo(new Point(404.16647, 692.886274), new Point(375.558791, 690.958885), new Point(351.628822, 699.751251));
            context.CubicBezierTo(new Point(327.698853, 708.521962), new Point(311.933223, 718.505418), new Point(313.644054, 728.575495));
            context.CubicBezierTo(new Point(315.376541, 738.645573), new Point(348.467033, 738.190793), new Point(367.242852, 733.014989));
            context.CubicBezierTo(new Point(387.36135, 727.471032), new Point(407.479848, 715.235349), new Point(405.812332, 704.060809));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey10()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(401.351179, 761.709298), true);
            context.CubicBezierTo(new Point(399.683663, 750.534758), new Point(371.075978, 748.607369), new Point(347.146009, 757.399734));
            context.CubicBezierTo(new Point(323.216041, 766.192105), new Point(307.450416, 776.153901), new Point(309.182902, 786.223979));
            context.CubicBezierTo(new Point(310.893734, 796.31571), new Point(343.984226, 795.839277), new Point(362.7817, 790.663473));
            context.CubicBezierTo(new Point(382.900198, 785.119516), new Point(403.018696, 772.905487), new Point(401.351179, 761.709298));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey11()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(403.581753, 818.08007), true);
            context.CubicBezierTo(new Point(401.935891, 806.905535), new Point(373.328212, 804.97814), new Point(349.376588, 813.770512));
            context.CubicBezierTo(new Point(325.468274, 822.541223), new Point(309.70265, 832.524679), new Point(311.413481, 842.594756));
            context.CubicBezierTo(new Point(313.145967, 852.664828), new Point(346.236454, 852.210054), new Point(365.012279, 847.03425));
            context.CubicBezierTo(new Point(385.130777, 841.490294), new Point(405.249275, 829.25461), new Point(403.581753, 818.08007));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey12()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(290.212179, 657.608519), true);
            context.CubicBezierTo(new Point(290.212179, 668.631464), new Point(266.693673, 677.575425), new Point(237.71784, 677.575425));
            context.CubicBezierTo(new Point(208.720347, 677.575425), new Point(185.223501, 668.631464), new Point(185.223501, 657.608519));
            context.CubicBezierTo(new Point(185.223501, 646.585574), new Point(208.720347, 637.663273), new Point(237.71784, 637.663273));
            context.CubicBezierTo(new Point(266.693673, 637.663273), new Point(290.212179, 646.585574), new Point(290.212179, 657.608519));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey13()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(292.442752, 717.487582), true);
            context.CubicBezierTo(new Point(292.442752, 728.510527), new Point(268.945906, 737.432829), new Point(239.948419, 737.432829));
            context.CubicBezierTo(new Point(210.950926, 737.432829), new Point(187.45408, 728.510527), new Point(187.45408, 717.487582));
            context.CubicBezierTo(new Point(187.45408, 706.464637), new Point(210.950926, 697.520677), new Point(239.948419, 697.520677));
            context.CubicBezierTo(new Point(268.945906, 697.520677), new Point(292.442752, 706.464637), new Point(292.442752, 717.487582));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey14()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(293.547211, 775.136066), true);
            context.CubicBezierTo(new Point(293.547211, 786.159011), new Point(270.050366, 795.102972), new Point(241.052878, 795.102972));
            context.CubicBezierTo(new Point(212.07704, 795.102972), new Point(188.580194, 786.159011), new Point(188.580194, 775.136066));
            context.CubicBezierTo(new Point(188.580194, 764.113121), new Point(212.07704, 755.190814), new Point(241.052878, 755.190814));
            context.CubicBezierTo(new Point(270.050366, 755.190814), new Point(293.547211, 764.113121), new Point(293.547211, 775.136066));
            context.EndFigure(true);
        }

        return geometry;
    }

    internal static StreamGeometry CreateKey15()
    {
        StreamGeometry geometry = new();
        using (StreamGeometryContext context = geometry.Open())
        {
            context.SetFillRule(FillRule.EvenOdd);
            context.BeginFigure(new Point(291.316638, 833.910667), true);
            context.CubicBezierTo(new Point(291.316638, 844.933612), new Point(267.819792, 853.877572), new Point(238.822299, 853.877572));
            context.CubicBezierTo(new Point(209.846467, 853.877572), new Point(186.327961, 844.933612), new Point(186.327961, 833.910667));
            context.CubicBezierTo(new Point(186.327961, 822.887721), new Point(209.846467, 813.943761), new Point(238.822299, 813.943761));
            context.CubicBezierTo(new Point(267.819792, 813.943761), new Point(291.316638, 822.887721), new Point(291.316638, 833.910667));
            context.EndFigure(true);
        }

        return geometry;
    }
}
