// SPDX-License-Identifier: MIT

#:package Avalonia@12.1.1

using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Avalonia;
using Avalonia.Media;

if (args.Length != 2)
{
    Console.Error.WriteLine(
        "Usage: dotnet run tools/generate-mia-phone-geometry.cs -- <mia.svg> <output.cs>");
    return 2;
}

string inputPath = Path.GetFullPath(args[0]);
string outputPath = Path.GetFullPath(args[1]);
XDocument document = XDocument.Load(inputPath, LoadOptions.PreserveWhitespace);
XElement root = document.Root
    ?? throw new InvalidDataException("The Mia SVG has no root element.");

double canvasWidth = ParseNumber(root.Attribute("width")?.Value, "width");
double canvasHeight = ParseNumber(root.Attribute("height")?.Value, "height");
double[] viewBox = ParseNumbers(root.Attribute("viewBox")?.Value, 4, "viewBox");
double scale = Math.Min(canvasWidth / viewBox[2], canvasHeight / viewBox[3]);
double viewportX = (canvasWidth - viewBox[2] * scale) / 2 - viewBox[0] * scale;
double viewportY = (canvasHeight - viewBox[3] * scale) / 2 - viewBox[1] * scale;

string[] sourceIds =
[
    "phone-body",
    "screen-window",
    "top-corner-left",
    "top-corner-right",
    "side-rocker",
    "joystick-outer",
    "joystick-inner",
    "legend-4",
    "legend-5",
    "legend-6",
    .. Enumerable.Range(0, 16).Select(index => $"key-{index}"),
];

Dictionary<string, XElement> definitions = root
    .Descendants()
    .Where(element => element.Attribute("id") is not null)
    .ToDictionary(element => element.Attribute("id")!.Value, StringComparer.Ordinal);

string sourceHash = Convert.ToHexStringLower(SHA256.HashData(File.ReadAllBytes(inputPath)));
StringBuilder output = new();
output.AppendLine("// <auto-generated />");
output.AppendLine("// Generated by tools/generate-mia-phone-geometry.cs from the PDF-derived paths in mia.svg.");
output.AppendLine();
output.AppendLine("using Avalonia;");
output.AppendLine("using Avalonia.Media;");
output.AppendLine();
output.AppendLine("namespace Mia.App.Controls;");
output.AppendLine();
output.AppendLine("internal static class MiaPhoneGeometry");
output.AppendLine("{");
output.AppendLine(CultureInfo.InvariantCulture, $"    internal const string SourceSha256 = \"{sourceHash}\";");
output.AppendLine(CultureInfo.InvariantCulture, $"    internal const double CanvasWidth = {Number(canvasWidth)};");
output.AppendLine(CultureInfo.InvariantCulture, $"    internal const double CanvasHeight = {Number(canvasHeight)};");
output.AppendLine();
output.AppendLine("    internal static Geometry CreateKey(int index) => index switch");
output.AppendLine("    {");
for (int index = 0; index < 16; index++)
{
    output.AppendLine(CultureInfo.InvariantCulture, $"        {index} => CreateKey{index}(),");
}
output.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(index)),");
output.AppendLine("    };");

foreach (string id in sourceIds)
{
    if (!definitions.TryGetValue(id, out XElement? element))
    {
        throw new InvalidDataException($"The Mia SVG is missing #{id}.");
    }

    string data = element.Attribute("d")?.Value
        ?? throw new InvalidDataException($"The Mia SVG element #{id} has no path data.");
    Matrix elementTransform = ParseMatrix(element.Attribute("transform")?.Value);
    Matrix outputTransform = new(
        elementTransform.M11 * scale,
        elementTransform.M12 * scale,
        elementTransform.M21 * scale,
        elementTransform.M22 * scale,
        elementTransform.M31 * scale + viewportX,
        elementTransform.M32 * scale + viewportY);
    PathGeometry geometry = PathGeometry.Parse(data);
    AppendGeometryFactory(output, MethodName(id), geometry, outputTransform);
}

output.AppendLine("}");
Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(
    outputPath,
    output.ToString().ReplaceLineEndings("\n"),
    new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
Console.WriteLine($"Generated {outputPath} from SHA-256 {sourceHash}.");
return 0;

static string MethodName(string id)
{
    if (id.StartsWith("key-", StringComparison.Ordinal))
    {
        return $"Key{id[4..]}";
    }

    return string.Concat(
        id.Split('-', StringSplitOptions.RemoveEmptyEntries)
            .Select(part => char.ToUpperInvariant(part[0]) + part[1..]));
}

static void AppendGeometryFactory(
    StringBuilder output,
    string name,
    PathGeometry source,
    Matrix transform)
{
    output.AppendLine();
    output.AppendLine(CultureInfo.InvariantCulture, $"    internal static StreamGeometry Create{name}()");
    output.AppendLine("    {");
    output.AppendLine("        StreamGeometry geometry = new();");
    output.AppendLine("        using (StreamGeometryContext context = geometry.Open())");
    output.AppendLine("        {");
    output.AppendLine(CultureInfo.InvariantCulture, $"            context.SetFillRule(FillRule.{source.FillRule});");

    foreach (PathFigure figure in source.Figures ?? [])
    {
        output.AppendLine(
            CultureInfo.InvariantCulture,
            $"            context.BeginFigure({PointSource(Transform(figure.StartPoint, transform))}, {Bool(figure.IsFilled)});");
        foreach (PathSegment segment in figure.Segments ?? [])
        {
            AppendSegment(output, segment, transform);
        }

        output.AppendLine(CultureInfo.InvariantCulture, $"            context.EndFigure({Bool(figure.IsClosed)});");
    }

    output.AppendLine("        }");
    output.AppendLine();
    output.AppendLine("        return geometry;");
    output.AppendLine("    }");
}

static void AppendSegment(StringBuilder output, PathSegment segment, Matrix transform)
{
    switch (segment)
    {
        case LineSegment line:
            output.AppendLine(
                CultureInfo.InvariantCulture,
                $"            context.LineTo({PointSource(Transform(line.Point, transform))});");
            break;
        case BezierSegment bezier:
            output.AppendLine(
                CultureInfo.InvariantCulture,
                $"            context.CubicBezierTo({PointSource(Transform(bezier.Point1, transform))}, " +
                $"{PointSource(Transform(bezier.Point2, transform))}, " +
                $"{PointSource(Transform(bezier.Point3, transform))});");
            break;
        case QuadraticBezierSegment quadratic:
            output.AppendLine(
                CultureInfo.InvariantCulture,
                $"            context.QuadraticBezierTo({PointSource(Transform(quadratic.Point1, transform))}, " +
                $"{PointSource(Transform(quadratic.Point2, transform))});");
            break;
        case PolyLineSegment polyLine:
            foreach (Point point in polyLine.Points ?? [])
            {
                output.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"            context.LineTo({PointSource(Transform(point, transform))});");
            }
            break;
        case PolyBezierSegment polyBezier:
            Points points = polyBezier.Points ?? [];
            if (points.Count % 3 != 0)
            {
                throw new InvalidDataException(
                    "A poly-Bezier segment does not contain complete point triplets.");
            }

            for (int index = 0; index < points.Count; index += 3)
            {
                output.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"            context.CubicBezierTo({PointSource(Transform(points[index], transform))}, " +
                    $"{PointSource(Transform(points[index + 1], transform))}, " +
                    $"{PointSource(Transform(points[index + 2], transform))});");
            }
            break;
        default:
            throw new InvalidDataException(
                $"Unsupported Mia SVG path segment: {segment.GetType().Name}.");
    }
}

static Point Transform(Point point, Matrix matrix) => matrix.Transform(point);

static Matrix ParseMatrix(string? value)
{
    if (string.IsNullOrWhiteSpace(value))
    {
        return Matrix.Identity;
    }

    Match match = Regex.Match(
        value,
        @"^\s*matrix\s*\(([^)]*)\)\s*$",
        RegexOptions.CultureInvariant);
    if (!match.Success)
    {
        throw new InvalidDataException($"Unsupported SVG transform: {value}");
    }

    double[] values = ParseNumbers(match.Groups[1].Value, 6, "matrix");
    return new Matrix(values[0], values[1], values[2], values[3], values[4], values[5]);
}

static double ParseNumber(string? value, string label)
{
    if (!double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out double result))
    {
        throw new InvalidDataException($"The SVG {label} is missing or invalid.");
    }

    return result;
}

static double[] ParseNumbers(string? value, int expectedCount, string label)
{
    double[] values = (value ?? "")
        .Split([' ', ','], StringSplitOptions.RemoveEmptyEntries)
        .Select(item => ParseNumber(item, label))
        .ToArray();
    if (values.Length != expectedCount)
    {
        throw new InvalidDataException(
            $"The SVG {label} needs {expectedCount} values, but has {values.Length}.");
    }

    return values;
}

static string PointSource(Point point) =>
    $"new Point({Number(point.X)}, {Number(point.Y)})";

static string Number(double value)
{
    double rounded = Math.Round(value, 6, MidpointRounding.AwayFromZero);
    if (rounded == 0)
    {
        rounded = 0;
    }

    return rounded.ToString("0.######", CultureInfo.InvariantCulture);
}

static string Bool(bool value) => value ? "true" : "false";
